Repository mysensors/MySensors, pull requests merged in 2018-09, with the labels that each got.

#1200 Fix SPIDEV on Armbian Stretch
  configure
  drivers/BCM/BCM.cpp
  drivers/BCM/BCM.h
  drivers/BCM/SPIBCM.cpp
  drivers/Linux/SPIDEV.cpp
  drivers/Linux/SPIDEV.h
  drivers/RF24/RF24.cpp
  drivers/RFM69/new/RFM69_new.cpp
  drivers/RFM95/RFM95.cpp
Labels: Linux

#1198 Allow flash strings in present() to save RAM
  core/MySensorsCore.cpp
  core/MySensorsCore.h
Labels: enhancement

#1205 Fix internal message forwarding
  core/MyTransport.cpp
Labels: bug
