Repository mysensors/MySensors, pull requests merged in 2018-02, with the labels that each got.

#1060 Fix smartSleep()
  core/MySensorsCore.cpp
Labels: bug

#1059 AVR: Harmonize code
  hal/architecture/AVR/MyHwAVR.cpp
  hal/architecture/AVR/MyHwAVR.h
Labels: AVR

#1042 Various CI-pipeline fixes
  .ci/doxygen.groovy
  .ci/gitler.groovy
  Documentation/doxygen.sh
  Documentation/mainpage.dox
Labels: CI, enhancement

#1056 Revamp the simple password flag and rPi fixes
  MyConfig.h
  configure
  core/MySigning.h
  hal/architecture/Linux/MyMainLinux.cpp
  hal/transport/MyTransportNRF5_ESB.cpp
  hal/transport/MyTransportRF24.cpp
  hal/transport/MyTransportRFM69.cpp
  keywords.txt
Labels: RPi, documentation, security

#1053 Linux: Serial minor update
  MyConfig.h
  configure
  drivers/Linux/StdInOutStream.cpp
  drivers/Linux/StdInOutStream.h
  examples_linux/mysgw.cpp
  hal/architecture/Linux/MyHwLinuxGeneric.cpp
  hal/architecture/Linux/MyHwLinuxGeneric.h
Labels: RPi

#1049 RFM69: Updates and optimizations
  MyConfig.h
  drivers/RFM69/new/RFM69_new.cpp
  drivers/RFM69/new/RFM69_new.h
  drivers/RFM69/new/RFM69registers_new.h
  hal/transport/RFM69/MyTransportRFM69.cpp
Labels: RFM69

#1018 Nvm fota
  MyConfig.h
  MySensors.h
  core/MyMessage.h
  core/MyOTAFirmwareUpdate.cpp
  core/MyOTAFirmwareUpdate.h
  drivers/NRF5/Flash.cpp
  drivers/NVM/VirtualPage.cpp
  examples/SecurityPersonalizer/SecurityPersonalizer.ino
  hal/architecture/NRF5/MyHwNRF5.cpp
Labels: enhancement
