Repository mysensors/MySensors, pull requests merged in 2018-03, with the labels that each got.

#1067 Add git commit message hook to the mystools bundle
  .mystools/hooks/commit-msg.sh
Labels: CI

#1076 Fix default IRQ pins on ESP8266 that prevent MCU from boot
  drivers/RFM69/new/RFM69_new.h
  drivers/RFM69/old/RFM69_old.h
  drivers/RFM95/RFM95.h
Labels: release-notes

#1061 Linux: Use config file for gateway settings
  MyConfig.h
  configure
  drivers/Linux/SoftEeprom.cpp
  drivers/Linux/SoftEeprom.h
  drivers/Linux/config.c
  drivers/Linux/config.h
  drivers/Linux/log.c
  drivers/Linux/log.h
  examples_linux/mysgw.cpp
  hal/architecture/Linux/MyHwLinuxGeneric.cpp
  hal/architecture/Linux/MyHwLinuxGeneric.h
  hal/architecture/Linux/MyMainLinuxGeneric.cpp
  initscripts/mysgw.systemd
  initscripts/mysgw.sysvinit
Labels: RPi
