Repository mysensors/MySensors, pull requests merged in 2019-04, with the labels that each got.

#1274 CI: Update Arduino IDE 1.8.9
  .ci/arduino.groovy
  core/Version.h
Labels: CI

#1273 Enable heartbeat for GW-only mode
  core/MySensorsCore.cpp
Labels: enhancement

#1275 Add CPU frequency to core debug info
  core/MySensorsCore.cpp
  core/MySensorsCore.h
Labels: enhancement

#1279 Code maintenance
  .ci/doxygen.groovy
  .mystools/README.md
  MyConfig.h
  MySensors.h
  configure
  core/MySensorsCore.cpp
  core/MySensorsCore.h
  core/MySigning.h
  core/MyTransport.cpp
  core/MyTransport.h
  hal/architecture/AVR/MyHwAVR.cpp
  hal/architecture/AVR/drivers/DigitalIO/DigitalIO.h
  hal/architecture/AVR/drivers/DigitalIO/DigitalPin.h
  hal/architecture/AVR/drivers/DigitalIO/I2cConstants.h
  hal/architecture/AVR/drivers/DigitalIO/PinIO.cpp
  hal/architecture/AVR/drivers/DigitalIO/PinIO.h
  hal/architecture/AVR/drivers/DigitalIO/SoftI2cMaster.cpp
  hal/architecture/AVR/drivers/DigitalIO/SoftI2cMaster.h
  hal/architecture/AVR/drivers/DigitalIO/SoftSPI.h
  hal/architecture/AVR/drivers/DigitalIO/attic/ADS7818.h
  hal/architecture/AVR/drivers/DigitalIO/attic/MCP320X.h
  hal/architecture/AVR/drivers/DigitalIO/attic/MCP355X.h
  hal/architecture/AVR/drivers/DigitalIO/boards/AvrDevelopersGpioPinMap.h
  hal/architecture/AVR/drivers/DigitalIO/boards/BobuinoGpioPinMap.h
  hal/architecture/AVR/drivers/DigitalIO/boards/GpioPinMap.h
  hal/architecture/AVR/drivers/DigitalIO/boards/LeonardoGpioPinMap.h
  hal/architecture/AVR/drivers/DigitalIO/boards/MegaGpioPinMap.h
  hal/architecture/AVR/drivers/DigitalIO/boards/SleepingBeautyGpioPinMap.h
  hal/architecture/AVR/drivers/DigitalIO/boards/Standard1284GpioPinMap.h
  hal/architecture/AVR/drivers/DigitalIO/boards/Teensy2GpioPinMap.h
  hal/architecture/AVR/drivers/DigitalIO/boards/Teensy2ppGpioPinMap.h
  hal/architecture/AVR/drivers/DigitalIO/boards/UnoGpioPinMap.h
  hal/architecture/AVR/drivers/DigitalIO/examples/DigitalPinBlink/DigitalPinBlink.ino
  hal/architecture/AVR/drivers/DigitalIO/examples/DigitalPinConfigToggle/DigitalPinConfigToggle.ino
  hal/architecture/AVR/drivers/DigitalIO/examples/DigitalPinReadWrite/DigitalPinReadWrite.ino
  hal/architecture/AVR/drivers/DigitalIO/examples/DigitalPinShiftOut/DigitalPinShiftOut.ino
  hal/architecture/AVR/drivers/DigitalIO/examples/PinIOBegin/PinIOBegin.ino
  hal/architecture/AVR/drivers/DigitalIO/examples/PinIOConfigToggle/PinIOConfigToggle.ino
  hal/architecture/AVR/drivers/DigitalIO/examples/PinIOReadWrite/PinIOReadWrite.ino
  hal/architecture/AVR/drivers/DigitalIO/examples/ScanI2cBus/ScanI2cBus.ino
  hal/architecture/AVR/drivers/DigitalIO/examples/SoftDS1307Utility/SoftDS1307Utility.ino
  hal/architecture/AVR/drivers/DigitalIO/examples/testArduino/testArduino.ino
  hal/architecture/AVR/drivers/DigitalIO/examples/testDigitalPin/testDigitalPin.ino
  hal/architecture/AVR/drivers/DigitalIO/examples/testFastDigital/testFastDigital.ino
  hal/architecture/AVR/drivers/DigitalIO/examples/testPinIO/testPinIO.ino
  hal/architecture/AVR/drivers/DigitalIO/examples/testSoftSPI/testSoftSPI.ino
  hal/architecture/ESP8266/MyHwESP8266.cpp
  hal/architecture/ESP8266/MyHwESP8266.h
  hal/architecture/Linux/MyHwLinuxGeneric.cpp
  hal/architecture/Linux/MyHwLinuxGeneric.h
  hal/architecture/MyHwHAL.h
  hal/architecture/NRF5/MyHwNRF5.cpp
  hal/architecture/SAMD/MyHwSAMD.h
  hal/architecture/Teensy3/MyHwTeensy3.h
Labels: maintenance

#1280 AVR: Fix frequency measurement
  hal/architecture/AVR/MyHwAVR.cpp
Labels: AVR, bug

#1281 Fix GW transport
  core/MySensorsCore.cpp
Labels: bug

#1286 Added getSleepRemaining to core
  core/MySensorsCore.cpp
  core/MySensorsCore.h
  hal/architecture/AVR/MyHwAVR.cpp
  hal/architecture/AVR/MyHwAVR.h
  hal/architecture/ESP32/MyHwESP32.h
  hal/architecture/ESP8266/MyHwESP8266.h
  hal/architecture/Linux/MyHwLinuxGeneric.h
  hal/architecture/NRF5/MyHwNRF5.h
  hal/architecture/SAMD/MyHwSAMD.h
  hal/architecture/STM32F1/MyHwSTM32F1.h
  hal/architecture/Teensy3/MyHwTeensy3.h
Labels: enhancement

#1288 Fix TransportHAL debug output
  hal/transport/MyTransportHAL.cpp
Labels: bug
