Repository mysensors/MySensors, pull requests merged in 2019-11, with the labels that each got.

#1358 Add MY_RS485_DE_INVERSE define to invert the device enable pin polarity
  MyConfig.h
  hal/transport/RS485/MyTransportRS485.cpp
  keywords.txt
Labels: enhancement, release-notes

#1365 Fix potential buffer overflow
  hal/architecture/Linux/drivers/core/GPIO.cpp
Labels: RPi

#1366 Fix double free
  hal/architecture/Linux/drivers/core/SoftEeprom.cpp
Labels: RPi

#1370 ESP8266: Update to 2.6.1
  hal/architecture/ESP8266/MyMainESP8266.cpp
Labels: CI, ESP8266

#1369 Add fuse chapter to signing troubleshooting
  core/MySigning.h
Labels: documentation

#1364 RPI: Add support for RPI4
  Makefile
  configure
  hal/architecture/Linux/drivers/BCM/bcm2835.c
  hal/architecture/Linux/drivers/BCM/bcm2835.h
Labels: RPi
