Repository mysensors/MySensors, pull requests merged in 2019-01, with the labels that each got.

#1247 RPI: Fix compilation error
  core/MySigningAtsha204Soft.cpp
Labels: RPi, bug

#1248 Add MQTT Wifi connection status check
  core/MyGatewayTransportMQTTClient.cpp
Labels: ESP32, ESP8266, MQTT

#1234 Add hwSPI to HAL
  MySensors.h
  hal/architecture/AVR/MyHwAVR.cpp
  hal/architecture/AVR/MyHwAVR.h
  hal/architecture/ESP32/MyHwESP32.h
  hal/architecture/ESP8266/MyHwESP8266.h
  hal/architecture/Linux/MyHwLinuxGeneric.h
  hal/architecture/NRF5/MyHwNRF5.h
  hal/architecture/SAMD/MyHwSAMD.h
  hal/architecture/STM32F1/MyHwSTM32F1.h
  hal/architecture/Teensy3/MyHwTeensy3.h
  hal/transport/RF24/driver/RF24.h
  hal/transport/RFM69/driver/new/RFM69_new.h
  hal/transport/RFM69/driver/old/RFM69_old.cpp
  hal/transport/RFM69/driver/old/RFM69_old.h
  hal/transport/RFM95/driver/RFM95.h
Labels: enhancement

#1251 Add unified HwDebugPrint()
  MySensors.h
  hal/architecture/AVR/MyHwAVR.cpp
  hal/architecture/ESP32/MyHwESP32.cpp
  hal/architecture/ESP8266/MyHwESP8266.cpp
  hal/architecture/Linux/MyHwLinuxGeneric.cpp
  hal/architecture/MyHwHAL.cpp
  hal/architecture/NRF5/MyHwNRF5.cpp
  hal/architecture/SAMD/MyHwSAMD.cpp
  hal/architecture/STM32F1/MyHwSTM32F1.cpp
  hal/architecture/Teensy3/MyHwTeensy3.cpp
Labels: enhancement

#1250 Maintenance: ethernet and MQTT code
  MyConfig.h
  core/MyGatewayTransport.h
  core/MyGatewayTransportEthernet.cpp
  core/MyGatewayTransportMQTTClient.cpp
  core/Version.h
Labels: ESP32, ESP8266, maintenance

#1252 Update recursive wait() call warning
  core/MySensorsCore.cpp
  core/MySensorsCore.h
Labels: enhancement

#1263 Cleanup: Remove RFM69 listenmode references
  MyConfig.h
Labels: maintenance
