Repository mysensors/MySensors, pull requests merged in 2020-04, with the labels that each got.

#1402 ESP32: Fix memory leak in crypto functions
  hal/crypto/ESP32/MyCryptoESP32.cpp
Labels: ESP32, bug, security

#1384 Update jenkinsfile to clean old jobs
  .ci/Jenkinsfile
Labels: CI

#1386 Update documentation retention
  .ci/doxygen.groovy
Labels: documentation

#1408 Fix STM32F1 capability indicator
  core/MyCapabilities.h
Labels: STM32F1, bug
